name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Ruff (warnings only)
        run: ruff check . --fix
        continue-on-error: true

      - name: Run tests with pytest
        run: |
          PYTHONPATH=. pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        run: docker build -t rag-service:ci .
